title: "TNT: Text-Conditioned Network with Transductive Inference for Few-Shot Video Classification"
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
github.zip_url: "https://www.bmvc2021-virtualconference.com/conference/papers/paper_1200.html"
theme: jekyll-theme-cayman
