title: "TNT: Text-Conditioned Network with Transductive Inference for Few-Shot Video Classification"
description: We formulate a text-based task conditioner to adapt video features to the few-shot learning task. Furthermore, our model follows a transductive setting to improve the task-adaptation ability of the model by using the support textual descriptions and query instances to update a set of class prototypes.
show_downloads: true
github.zip_url: "https://www.bmvc2021-virtualconference.com/conference/papers/paper_1200.html"
theme: jekyll-theme-cayman
